sast:
  #reportportal:
  #  rp_host:
  #  rp_token:
  #  rp_project_name:
  #  rp_launch_name:
  project_name: $project_name
  environment: $environment
  html_report: true
  language: python

basic:
  target_host: $host
  target_port: $port
  protocol: $protocol
  project_name: $project_name
  environment: $environment
  html_report: true
  junit_report: true
  sslyze: true
  masscan:
    inclusions: 0-65535
    exclusions: 80,443
  zap:
    scan_types: xss,sqli

tools:
  target_host: $host
  target_port: $port
  protocol: $protocol
  project_name: $project_name
  environment: $environment
  html_report: true
  junit_report: true
  sslyze: true
  masscan:
    inclusions: 0-65535
    exclusions: 443
  nmap:
    inclusions: T:0-65535
    nse_scripts: ssl-date,http-mobileversion-checker,http-robots.txt
    params: -v -A
  zap:
    scan_types: all,sqli,xss
  nikto:
    param: -Plugins @@ALL;-@@EXTRAS;-sitefiles;tests(report:500) -T 123x
  w3af:
    config_file: /tmp/w3af_full_audit.w3af

long_running:
  target_host: $host
  target_port: $port
  protocol: $protocol
  project_name: $project_name
  environment: $environment
  html_report: true
  w3af:
    config_file: /tmp/w3af_full_audit.w3af

ptai: # Name of the scan
  jira:
    url: https://jira.com     # Url to Jira
    username: some.dude       # User to create tickets
    password: password        # password to user in Jira
    jira_project: XYZC        # Jira project ID
    assignee: some.dude       # Jira id of default assignee
    issue_type: Bug           # Jira issue type (Default: Bug)
    labels: some,label        # Comaseparated list of lables for ticket
    watchers: another.dude    # Comaseparated list of Jira IDs for watchers
    jira_epic_key: XYZC-123   # Jira epic key (or id)
  ptai:
    # name of html report that to create jira tickets from
    report_name: NAME_OF_REPORT
